name: 夸克网盘自动签到脚本

on:
  schedule:
    - cron: '5 2 * * *'
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
          cache-dependency-glob: false

      - name: Check UV version
        run: uv --version

      - name: Sync dependencies with UV
        run: uv sync

      - name: Run Python script with UV (retry up to 3 times)
        env:
          QUARK_KPS: ${{ secrets.QUARK_KPS }}
          QUARK_SIGN: ${{ secrets.QUARK_SIGN }}
          QUARK_VCODE: ${{ secrets.QUARK_VCODE }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          for i in 1 2 3; do
            uv run main.py && break
            echo "Attempt $i failed, retrying in 10 seconds..."
            sleep 10
          done
